//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient.CovidServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CovidServiceReference.IRegisterService")]
    public interface IRegisterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/AddPatient", ReplyAction="http://tempuri.org/IRegisterService/AddPatientResponse")]
        void AddPatient(Patient.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/AddPatient", ReplyAction="http://tempuri.org/IRegisterService/AddPatientResponse")]
        System.Threading.Tasks.Task AddPatientAsync(Patient.Patient patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/GetPatients", ReplyAction="http://tempuri.org/IRegisterService/GetPatientsResponse")]
        Patient.Patient[] GetPatients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/GetPatients", ReplyAction="http://tempuri.org/IRegisterService/GetPatientsResponse")]
        System.Threading.Tasks.Task<Patient.Patient[]> GetPatientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterServiceChannel : ServiceClient.CovidServiceReference.IRegisterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterServiceClient : System.ServiceModel.ClientBase<ServiceClient.CovidServiceReference.IRegisterService>, ServiceClient.CovidServiceReference.IRegisterService {
        
        public RegisterServiceClient() {
        }
        
        public RegisterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddPatient(Patient.Patient patient) {
            base.Channel.AddPatient(patient);
        }
        
        public System.Threading.Tasks.Task AddPatientAsync(Patient.Patient patient) {
            return base.Channel.AddPatientAsync(patient);
        }
        
        public Patient.Patient[] GetPatients() {
            return base.Channel.GetPatients();
        }
        
        public System.Threading.Tasks.Task<Patient.Patient[]> GetPatientsAsync() {
            return base.Channel.GetPatientsAsync();
        }
    }
}
